# Generated by Django 3.2.5 on 2021-08-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_questionnaire_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'UserAnswer', 'verbose_name_plural': 'UserAnswers'},
        ),
        migrations.AlterModelOptions(
            name='userquestionnaire',
            options={'verbose_name': 'UserQuestionnaire', 'verbose_name_plural': 'UserQuestionnaires'},
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
